version: "3.8"
services:
  parser:
    image: rsiacsparse/parser
    environment:
      - PATH_TO_FILE_DATABASE=postgresql://postgres:postgres@postgres:5432/postgres
      - RESOLUTIONS_URL=https://iacs.flumeserver.co.za/wp-json/wp/v2/publications?sections=?&per_page=10&page=?&status=publish&orderby=menu_order&order=asc&acf_format=standard
      - SECTION_NUMBER_START=0
      - SECTION_NUMBER_END=150
      - PROCEDURES_URL=https://iacs.org.uk/membership/procedures
      - POSITION_PAPERS_URL=https://iacs.org.uk/about-us/position-papers
      - HOST_EMAIL_SERVER=
      - PORT_EMAIL_SERVER=
      - USERNAME_EMAIL_SERVER=
      - PASSWORD_EMAIL_SERVER=
      - NOTIFICATION_EMAIL_ADDRESS=
      - NOTIFICATION_EMAIL_PASSWORD=
      - EMAILS_TO_NOTIFY=
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
